name: ecotrack
description: "EcoTrack - Neighborhood Waste and Recycling Coordination System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.2

  # HTTP client
  http: ^1.2.2

  # Secure token storage
  flutter_secure_storage: ^9.2.2

  # Date formatting
  intl: ^0.19.0

  # URL launcher (for maps)
  url_launcher: ^6.3.1

  # Image picker
  image_picker: ^1.1.2

  # Cached network image
  cached_network_image: ^3.4.1

  # Flutter map (OpenStreetMap)
  flutter_map: ^7.0.2

  # Lat/Lng
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
